# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote',
        ),
    ]
