# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ing',
            new_name='Inges',
        ),
        migrations.RenameField(
            model_name='inges',
            old_name='ing_text',
            new_name='ing',
        ),
    ]
