# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171119_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inges',
            name='inges_text',
            field=models.CharField(max_length=200, verbose_name=b'\xed\x95\x9c\xea\xb8\x80'),
        ),
    ]
