# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171119_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inges',
            name='inges_text',
            field=models.CharField(max_length=200, verbose_name=b'\xed\x95\x99\xea\xb5\x90'),
        ),
    ]
